pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'Gnomes'
include 'core', 'lwjgl3'
if (!startParameter.projectProperties.containsKey('skipAndroid')) {
    include 'android'
}
