plugins { id 'application' }

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

sourceSets.main.resources.srcDirs += [rootProject.file('assets').path]

application {
    mainClass = 'com.enhort.gnomes.lwjgl3.Lwjgl3Launcher'
}

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
}

run {
    workingDir = rootProject.file('assets')
    ignoreExitValue = true
}
